## Data Analysis Exploration
1. importar los archivos
1. estudiar los datos que contienen
1. asegurarte de que los tipos de datos sean correctos
1. identificar los 10 principales barrios en términos de finalización del recorrido
1. hacer gráficos: empresas de taxis y número de viajes, los 10 barrios principales por número de finalizaciones
1. sacar conclusiones basadas en cada gráfico y explicar los resultados

In [1]:
#Importar librerias necesarias
import pandas as pd 
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# 1. Importar data frames
df_company = pd.read_csv('moved_project_sql_result_01.csv')
df_location = pd.read_csv('moved_project_sql_result_04.csv')
# 2. Analizar data frames
df_company.info()
print()
df_location.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_name  64 non-null     str
 1   trips_amount  64 non-null     int64
dtypes: int64(1), str(1)
memory usage: 2.5 KB

<class 'pandas.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dropoff_location_name  94 non-null     str
 1   average_trips          94 non-null     float64
dtypes: float64(1), str(1)
memory usage: 2.6 KB

In [ ]:
# 3. Transformar el average_trip  int
df_location['average_trips'] = df_location['average_trips'].round().astype(int)

In [ ]:
# 4. Organizar y graficar el data frame basado en average_trip los top 10 

df_order_location = df_location.sort_values(by='average_trips', ascending=False).head(10)

pivot_df = df_order_location.pivot( #Cambiar la forma de la tabla para graficar
    #index='average_trips',
    columns='dropoff_location_name',
    values='average_trips'
)

pivot_df.plot(kind='bar', figsize=(14, 6), rot=0) #rot=0 para mantener los numeros de los meses horizontal
plt.xlabel('Dropoff Location name')
plt.ylabel('Average trips quantity')
plt.title('Average trips per Location')
plt.legend(title='Location')
plt.tight_layout()
plt.show()

  dropoff_location_name  average_trips
0                  Loop          10727
1           River North           9524
2         Streeterville           6665
3             West Loop           5164
4                O'Hare           2547
5             Lake View           2421
6            Grant Park           2069
7         Museum Campus           1510
8            Gold Coast           1364
9    Sheffield & DePaul           1260

In [ ]:
# 5. Organizar y graficar los 10 barrios principales por número de finalizaciones
df_order_company = df_company.groupby('company_name')['trips_amount'].sum().sort_values(ascending=False).reset_index()
df_order_company.head(10)

                        company_name  trips_amount
0                          Flash Cab         19558
1          Taxi Affiliation Services         11422
2                   Medallion Leasin         10367
3                         Yellow Cab          9888
4    Taxi Affiliation Service Yellow          9299
5          Chicago Carriage Cab Corp          9181
6                       City Service          8448
7                           Sun Taxi          7701
8          Star North Management LLC          7455
9  Blue Ribbon Taxi Association Inc.          5953